### ISSUE TITLE
WXS schema schema/htmlbook.xsd failed to compile (ailed to load external entity "http://www.w3.org/2001/xml.xsd")

### ISSUE THREAD

**Issue by connerbw** [oreillymedia/HTMLBook#217]
Steps to reproduce:

```
git clone https://github.com/oreillymedia/HTMLBook.git
cd HTMLBook
xmllint --noout --schema schema/htmlbook.xsd samples/alices_adventures_in_wonderland.html
```

Output:

```
warning: failed to load external entity "http://www.w3.org/2001/xml.xsd"
schema/svg/xlink.xsd:27: element import: Schemas parser warning : Element '{http://www.w3.org/2001/XMLSchema}import': Failed to locate a schema at location 'http://www.w3.org/2001/xml.xsd'. Skipping the import.
schema/svg/xlink.xsd:171: element attribute: Schemas parser error : attribute use (unknown), attribute 'ref': The QName value '{http://www.w3.org/XML/1998/namespace}lang' does not resolve to a(n) attribute declaration.
schema/svg/SVG.xsd:337: element attribute: Schemas parser error : attribute use (unknown), attribute 'ref': The QName value '{http://www.w3.org/XML/1998/namespace}base' does not resolve to a(n) attribute declaration.
schema/svg/SVG.xsd:343: element attribute: Schemas parser error : attribute use (unknown), attribute 'ref': The QName value '{http://www.w3.org/XML/1998/namespace}lang' does not resolve to a(n) attribute declaration.
schema/svg/SVG.xsd:344: element attribute: Schemas parser error : attribute use (unknown), attribute 'ref': The QName value '{http://www.w3.org/XML/1998/namespace}space' does not resolve to a(n) attribute declaration.
schema/svg/SVG.xsd:1389: element attribute: Schemas parser error : attribute use (unknown), attribute 'ref': The QName value '{http://www.w3.org/XML/1998/namespace}space' does not resolve to a(n) attribute declaration.
WXS schema schema/htmlbook.xsd failed to compile
```

Help?

**Comment by gimsieke** [comment]
I’d rather use the file that is guaranteed to remain available (unless someone removes it from this repo), [xml.xsd](https://github.com/oreillymedia/HTMLBook/blob/master/schema/svg/xml.xsd). See PR #218

**Comment by jenstroeger** [comment]
I think I just encountered a similar problem using Python and [lxml](https://github.com/lxml/lxml):
```
Python 3.7.9 (default, Sep  6 2020, 16:32:30) 
[Clang 10.0.1 (clang-1001.0.46.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import lxml.etree
>>> lxml.etree.XMLSchema(file="htmlbook.xsd")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "src/lxml/xmlschema.pxi", line 88, in lxml.etree.XMLSchema.__init__
lxml.etree.XMLSchemaParseError: attribute use (unknown), attribute 'ref': The QName value '{http://www.w3.org/XML/1998/namespace}lang' does not resolve to a(n) attribute declaration., line 171
```
@gimsieke<sup>*</sup>, your [suggested workaround](https://github.com/oreillymedia/HTMLBook/issues/217#issuecomment-422927551) didn’t work for me, but considering that [`svg/xml.xsd`](https://github.com/oreillymedia/HTMLBook/tree/master/schema/svg) is checked into the repo I changed this line

https://github.com/oreillymedia/HTMLBook/blob/465453a7663609d241045288a3d6a619e8079fa2/schema/svg/xlink.xsd#L27

to
```xml
 <xs:import namespace="http://www.w3.org/XML/1998/namespace" schemaLocation="xml.xsd"/>
```
and I could load the schema file:
```
>>> lxml.etree.XMLSchema(file="htmlbook.xsd")
<lxml.etree.XMLSchema object at 0x10f913a70>
```

—————
<sup>*</sup> Hallo nach Leebsch vonnem annern Sachsn! ☺️

**Comment by gimsieke** [comment]
Isn’t that exactly what I suggested in https://github.com/gimsieke/HTMLBook/commit/04ab437ea32962e84d817c5d7d776a6d2caf8f96, mei Guudsder?

**Comment by jenstroeger** [comment]
Indeed you did 👍🏼
